# These are supported funding model platforms

# Replace these with your actual funding profiles
# Uncomment and update the platforms you use:

# github: [your-github-username]
# patreon: your-patreon-username
# open_collective: your-open-collective-name
# ko_fi: your-kofi-username
# tidelift: pypi/your-package-name
# community_bridge: project-name
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
# otechie: your-otechie-username
# lfx_crowdfunding: project-name
# custom: ['https://your-website.com/donate', 'https://another-funding-site.com']